# CURRENTLY DONT HAVE A DONATION LINK AT THE MOMENT, VOLUNTEERS ARE HIGHLY WELCOME 
# DISCORD INVITE LINK: https://www.discord.fnbubbles420.org/invite
github: [bubblesthedev, fnbubbles420org] # GitHub Sponsors-enabled usernames
custom: ['https://fnbubbles420.org/volunteer','https://discord.gg/WvqTu92aMs'] # Volunteer with fnbubbles420 org / Discord link
