# DISCORD INVITE LINK: https://www.discord.fnbubbles420.org/invite
github: [bubblesthedev, fnbubbles420org] # GitHub Sponsors-enabled usernames
custom: ['https://fnbubbles420.org','https://fnbubbles420.org/volunteer','https://discord.gg/bjbmWaP5p8','https://fnbubbles420.org/donate'] # Donation link , Volunteer link / Discord link
