# DISCORD INVITE LINK: https://www.discord.fnbubbles420.org/invite
github: [bubblesthedev, fnbubbles420org] # GitHub Sponsors-enabled usernames
custom: ['https://fnbubbles420.org','https://fnbubbles420.org/volunteer','https://discord.gg/bjbmWaP5p8','https://www.paypal.com/donate/?hosted_button_id=8MXYY8S8TLP9A'] # Donation link , Volunteer link / Discord link
